FROM oven/bun:1.1.38-alpine AS base

WORKDIR /home/bun/app

COPY package.json bun.lockb ./
COPY packages/astro/package.json ./packages/astro/package.json
COPY packages/shared/package.json ./packages/shared/package.json

FROM base AS prod-deps
RUN bun install --production

FROM base AS build-deps
RUN bun install

FROM build-deps AS build

COPY packages/astro ./packages/astro
COPY packages/shared ./packages/shared

WORKDIR /home/bun/app/packages/astro

ENV ASTRO_TELEMETRY_DISABLED=1

RUN bun run build

FROM base AS runtime

COPY --from=prod-deps /home/bun/app/node_modules/ ./node_modules/
COPY --from=build /home/bun/app/packages/astro/dist/ ./dist/

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["bun", "run", "./dist/server/entry.mjs"]
