# https://grafana.com/docs/tempo/latest/configuration/

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_format: "logfmt"
  log_level: "warn"

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
  log_received_spans:
    enabled: true # debugging
    include_all_attributes: true
    filter_by_status_error: true
  log_discarded_spans:
    enabled: true # debugging
    include_all_attributes: true
    filter_by_status_error: true
  metric_received_spans:
    enabled: true # debugging
    root_only: false

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal

# https://grafana.com/docs/tempo/latest/configuration/#metrics-generator
# I think this should point to the remote-write endpoint of mimir?
metrics_generator:
  storage:
    path: /var/tempo/metrics
