import { cookies } from 'next/headers'
import { type Theme, themeColors } from "@/utils/theme";
import { panda } from "styled-system/jsx";
import "@/index.css";
import NavBar from "@/components/navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const theme = ((await cookies()).get("theme")?.value || "system") as Theme;
const color = {
  light: themeColors.light,
  dark: themeColors.dark,
  system: "",
}[theme];

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className={(theme ?? "dark")}>
    <head>
      <meta charSet="UTF-8" />
      <meta name="description" content="Discover and sign up for volunteering shifts at De Sering!" />
      <meta name="viewport" content="width=device-width" />
      <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      <meta name="theme-color" content={color} />
      <meta name="darkreader-lock" />
      <title>{metadata.title}</title>
      {
        // only add this script if the theme is set to system
        // this avoids a flash of light theme on page load
        theme === "system" && (
          <script>
            const darkMediaQuery =
            window.matchMedia("(prefers-color-scheme:dark)");
            darkMediaQuery.matches &&
            document.documentElement.classList.add("dark");
          </script>
        )
      }
      {/*<script>*/}
      {/*  import { applyTheme } from "~/utils/theme";*/}
      {/*  applyTheme();*/}
      {/*  window*/}
      {/*    .matchMedia("(prefers-color-scheme: dark)")*/}
      {/*    .addEventListener("change", applyTheme);*/}
      {/*</script>*/}
    </head>
    <panda.body backgroundColor={{ base: "gray.4", _dark: "gray.2" }}>
      {children}
    </panda.body>
    </html>
  )
};
