/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Amsterdam';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    announcements: Announcement;
    'webcal-tokens': WebcalToken;
    'event-templates': EventTemplate;
    events: Event;
    locations: Location;
    roles: Role;
    sections: Section;
    signups: Signup;
    tags: Tag;
    'user-notification-preferences': UserNotificationPreference;
    users: User;
    skills: Skill;
    'skill-awards': SkillAward;
    messages: Message;
    'message-deliveries': MessageDelivery;
    'regular-card-views': RegularCardView;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    events: {
      sections: 'sections';
      roles: 'roles';
      signups: 'signups';
    };
    roles: {
      signups: 'signups';
    };
    sections: {
      roles: 'roles';
    };
    skills: {
      awards: 'skill-awards';
    };
    messages: {
      deliveries: 'message-deliveries';
    };
  };
  collectionsSelect: {
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'webcal-tokens': WebcalTokensSelect<false> | WebcalTokensSelect<true>;
    'event-templates': EventTemplatesSelect<false> | EventTemplatesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    signups: SignupsSelect<false> | SignupsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'user-notification-preferences': UserNotificationPreferencesSelect<false> | UserNotificationPreferencesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    'skill-awards': SkillAwardsSelect<false> | SkillAwardsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'message-deliveries': MessageDeliveriesSelect<false> | MessageDeliveriesSelect<true>;
    'regular-card-views': RegularCardViewsSelect<false> | RegularCardViewsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'volunteer-settings': VolunteerSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'volunteer-settings': VolunteerSettingsSelect<false> | VolunteerSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'send-event-signup-confirmation-email': TaskSendEventSignupConfirmationEmail;
      'process-ended-shifts': TaskProcessEndedShifts;
      'send-volunteer-message': TaskSendVolunteerMessage;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('neutral' | 'info' | 'warning' | 'error' | 'success') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webcal-tokens".
 */
export interface WebcalToken {
  id: number;
  token: string;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  preferredName: string;
  phoneNumber?: string | null;
  /**
   * Use Always for staff and coordinators who should get the perks regardless of shifts.
   */
  regularOverride?: ('auto' | 'always' | 'never') | null;
  roles?: ('admin' | 'editor' | 'volunteer') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-templates".
 */
export interface EventTemplate {
  id: number;
  template_title: string;
  event_title: string;
  start_time: string;
  start_time_tz: SupportedTimezones;
  end_time: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: (number | Tag)[] | null;
  locations?: (number | Location)[] | null;
  /**
   * Makes events from this template trainings: attendees earn these skills.
   */
  skills?: (number | Skill)[] | null;
  sections?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        roles: {
          title: string;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          /**
           * The maximum number of signups allowed for this role, 0 for unlimited
           */
          maxSignups: number;
          signups?:
            | {
                user: number | User;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Add roles that are not specific to a section
   */
  roles?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * The maximum number of signups allowed for this role, 0 for unlimited
         */
        maxSignups: number;
        signups?:
          | {
              user: number | User;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  title: string;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Something a volunteer can learn, in a training or on a shift. Volunteers see each skill they have as a badge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * An emoji, e.g. 🔪 or ☕
   */
  badge: string;
  title: string;
  /**
   * What a volunteer learns. Doubles as the teaching guide for whoever runs the training.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Skills a volunteer needs first. We only invite people who have all of them.
   */
  prerequisites?: (number | Skill)[] | null;
  /**
   * Invite volunteers to learn this once they have done this many shifts. 0 = from the start.
   */
  inviteAfterShifts: number;
  awards?: {
    docs?: (number | SkillAward)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Who has which skill. Trainings add rows automatically once the training is over; you can also add one by hand when someone learns a skill on a shift.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-awards".
 */
export interface SkillAward {
  id: number;
  user: number | User;
  skill: number | Skill;
  source: 'training' | 'coordinator';
  /**
   * The training or shift where it was learned, if any.
   */
  event?: (number | null) | Event;
  awardedAt: string;
  /**
   * Empty when the after-shift job awarded it.
   */
  awardedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  start_date: string;
  end_date: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?: (number | Tag)[] | null;
  /**
   * Makes this a training: everyone who attends earns these skills (shown as badges) once it is over.
   */
  skills?: (number | Skill)[] | null;
  locations?: (number | Location)[] | null;
  sections?: {
    docs?: (number | Section)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  roles?: {
    docs?: (number | Role)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  signups?: {
    docs?: (number | Signup)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  event: number | Event;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  roles?: {
    docs?: (number | Role)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  event?: (number | null) | Event;
  section?: (number | null) | Section;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The maximum number of signups allowed for this role, 0 for unlimited
   */
  maxSignups: number;
  signups?: {
    docs?: (number | Signup)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups".
 */
export interface Signup {
  id: number;
  event?: (number | null) | Event;
  role: number | Role;
  user: number | User;
  /**
   * Leave empty unless someone did not show up: an unmarked signup counts as attended once the shift is over.
   */
  attendance?: ('attended' | 'no-show') | null;
  afterShiftProcessedAt?: string | null;
  title?: string | null;
  totalShifts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notification-preferences".
 */
export interface UserNotificationPreference {
  id: number;
  user: number | User;
  type: string;
  channel: string;
  preference: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email a group of volunteers, picked by what they have done. Nothing is sent until you press Send on the message.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  subject: string;
  /**
   * Plain text; leave an empty line between paragraphs. {name} becomes the volunteer's name. A link to their volunteering page and how to unsubscribe are added below.
   */
  body: string;
  /**
   * Who receives this. Every filter you fill in must match; leave a filter empty to ignore it. Volunteers who switched off invitations never receive it.
   */
  audience?: {
    minShifts?: number | null;
    maxShifts?: number | null;
    activeWithinDays?: number | null;
    /**
     * Finds people we may be losing.
     */
    inactiveForDays?: number | null;
    hasSkills?: (number | Skill)[] | null;
    lacksSkills?: (number | Skill)[] | null;
    regulars?: ('any' | 'only' | 'exclude') | null;
    /**
     * e.g. role contains "coordinator", on a Tuesday, in the last 90 days.
     */
    didShift?: {
      roleContains?: string | null;
      weekday?: ('sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday') | null;
      tags?: (number | Tag)[] | null;
      withinDays?: number | null;
    };
  };
  status: 'draft' | 'sending' | 'sent';
  sentAt?: string | null;
  sentBy?: (number | null) | User;
  recipientCount?: number | null;
  deliveries?: {
    docs?: (number | MessageDelivery)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every email the volunteer features sent, and to whom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-deliveries".
 */
export interface MessageDelivery {
  id: number;
  user: number | User;
  kind: 'message' | 'after-shift';
  message?: (number | null) | Message;
  /**
   * The shift an after-shift email was about.
   */
  signup?: (number | null) | Signup;
  subject: string;
  status: 'sent' | 'failed';
  error?: string | null;
  sentAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regular-card-views".
 */
export interface RegularCardView {
  id: number;
  user: number | User;
  viewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'send-event-signup-confirmation-email' | 'process-ended-shifts' | 'send-volunteer-message';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'send-event-signup-confirmation-email' | 'process-ended-shifts' | 'send-volunteer-message') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'announcements';
        value: number | Announcement;
      } | null)
    | ({
        relationTo: 'event-templates';
        value: number | EventTemplate;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'signups';
        value: number | Signup;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'skill-awards';
        value: number | SkillAward;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webcal-tokens_select".
 */
export interface WebcalTokensSelect<T extends boolean = true> {
  token?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-templates_select".
 */
export interface EventTemplatesSelect<T extends boolean = true> {
  template_title?: T;
  event_title?: T;
  start_time?: T;
  start_time_tz?: T;
  end_time?: T;
  description?: T;
  tags?: T;
  locations?: T;
  skills?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        roles?:
          | T
          | {
              title?: T;
              description?: T;
              maxSignups?: T;
              signups?:
                | T
                | {
                    user?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  roles?:
    | T
    | {
        title?: T;
        description?: T;
        maxSignups?: T;
        signups?:
          | T
          | {
              user?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  start_date?: T;
  end_date?: T;
  description?: T;
  tags?: T;
  skills?: T;
  locations?: T;
  sections?: T;
  roles?: T;
  signups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  title?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  event?: T;
  section?: T;
  title?: T;
  description?: T;
  maxSignups?: T;
  signups?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  event?: T;
  title?: T;
  description?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signups_select".
 */
export interface SignupsSelect<T extends boolean = true> {
  event?: T;
  role?: T;
  user?: T;
  attendance?: T;
  afterShiftProcessedAt?: T;
  title?: T;
  totalShifts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notification-preferences_select".
 */
export interface UserNotificationPreferencesSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  channel?: T;
  preference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  preferredName?: T;
  phoneNumber?: T;
  regularOverride?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  description?: T;
  prerequisites?: T;
  inviteAfterShifts?: T;
  awards?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skill-awards_select".
 */
export interface SkillAwardsSelect<T extends boolean = true> {
  user?: T;
  skill?: T;
  source?: T;
  event?: T;
  awardedAt?: T;
  awardedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  subject?: T;
  body?: T;
  audience?:
    | T
    | {
        minShifts?: T;
        maxShifts?: T;
        activeWithinDays?: T;
        inactiveForDays?: T;
        hasSkills?: T;
        lacksSkills?: T;
        regulars?: T;
        didShift?:
          | T
          | {
              roleContains?: T;
              weekday?: T;
              tags?: T;
              withinDays?: T;
            };
      };
  status?: T;
  sentAt?: T;
  sentBy?: T;
  recipientCount?: T;
  deliveries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-deliveries_select".
 */
export interface MessageDeliveriesSelect<T extends boolean = true> {
  user?: T;
  kind?: T;
  message?: T;
  signup?: T;
  subject?: T;
  status?: T;
  error?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regular-card-views_select".
 */
export interface RegularCardViewsSelect<T extends boolean = true> {
  user?: T;
  viewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-settings".
 */
export interface VolunteerSetting {
  id: number;
  regularMinShifts: number;
  regularWindowDays: number;
  /**
   * Shown on the regular card, one line each.
   */
  perks?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cardNote?: string | null;
  milestones?:
    | {
        shifts: number;
        label: string;
        badge: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Off by default. Shifts that end while this is off never get an email later.
   */
  afterShiftEmails?: boolean | null;
  /**
   * Time for coordinators to mark no-shows before badges and emails go out.
   */
  afterShiftDelayHours: number;
  afterShiftSubject: string;
  /**
   * {name} = their name, {event} = the shift, {shifts} = how many shifts they have done. Progress and next steps are added below automatically.
   */
  afterShiftBody: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-settings_select".
 */
export interface VolunteerSettingsSelect<T extends boolean = true> {
  regularMinShifts?: T;
  regularWindowDays?: T;
  perks?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cardNote?: T;
  milestones?:
    | T
    | {
        shifts?: T;
        label?: T;
        badge?: T;
        id?: T;
      };
  afterShiftEmails?: T;
  afterShiftDelayHours?: T;
  afterShiftSubject?: T;
  afterShiftBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-event-signup-confirmation-email".
 */
export interface TaskSendEventSignupConfirmationEmail {
  input: {
    signupId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProcess-ended-shifts".
 */
export interface TaskProcessEndedShifts {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-volunteer-message".
 */
export interface TaskSendVolunteerMessage {
  input: {
    messageId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}