name: lint

on:
  push:

jobs:
  biome:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bunx biome format ./packages
